# Google Cloud Build configuration for Query Optimizer API
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/query-optimizer-api:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/query-optimizer-api:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/query-optimizer-api:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/query-optimizer-api:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'query-optimizer-api',
      '--image', 'gcr.io/$PROJECT_ID/query-optimizer-api:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '80',
      '--memory', '512Mi',
      '--cpu', '1',
      '--max-instances', '10',
      '--set-env-vars', 'RAILS_ENV=production',
      '--set-cloudsql-instances', '$PROJECT_ID:us-central1:query-optimizer-db'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/query-optimizer-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/query-optimizer-api:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout for the entire build
timeout: '1200s'
