version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/query_optimizer_development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - ./log:/rails/log
      - ./tmp:/rails/tmp
    stdin_open: true
    tty: true
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=query_optimizer_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_dev_data:
  redis_dev_data:
  bundle_cache:
